let SNEAKERS = [
	{
		id: "IMAG1",
		colorway: "Pine Green",
		imageUrl:
			"https://images.mcan.sh/b_auto,c_pad,f_auto,h_400,q_auto,w_400/v1/prject/almarai",
		model: "Blazer Low 77 Vintage",
		brand: "Nike",
	},
	{
		id: "IMAG2",
		colorway: "Reverse Infrared",
		imageUrl:
			"https://images.mcan.sh/b_auto,c_pad,f_auto,h_400,q_auto,w_400/v1/prject/almarai-new",
		model: "Air Max 90",
		brand: "Nike",
	},
	{
		id: "IMAG3",
		colorway: "White/Black/Desert",
		imageUrl:
			"https://images.mcan.sh/b_auto,c_pad,f_auto,h_400,q_auto,w_400/v1/prject/Burger",
		model: "Court Legacy",
		brand: "Nike",
	},
	{
		id: "IMAG5",
		colorway: "Beluga 2.0",
		imageUrl:
			"https://images.mcan.sh/b_auto,c_pad,f_auto,h_400,q_auto,w_400/v1/prject/dior",
		model: "Yeezy 350 v2",
		brand: "Adidas",
	},
	{
		id: "IMAG6",
		colorway: "Pumpkin Spice",
		imageUrl:
			"https://images.mcan.sh/b_auto,c_pad,f_auto,h_400,q_auto,w_400/v1/prject/expert",
		model: "Grid SD",
		brand: "Saucony",
	},
	{
		id: "IMAG7",
		colorway: "Golden Coast",
		imageUrl:
			"https://images.mcan.sh/b_auto,c_pad,f_auto,h_400,q_auto,w_400/v1/prject/welcome",
		model: "Checkerboard Slip-On",
		brand: "Vans",
	},
	{
		id: "IMAG8",
		colorway: "Have a Nike Day",
		imageUrl:
			"https://images.mcan.sh/b_auto,c_pad,f_auto,h_400,q_auto,w_400/v1/prject/hello",
		model: "Air Max 1",
		brand: "Nike",
	},
];

export default SNEAKERS